### ISSUE TITLE
Caching go mod download layer

### ISSUE THREAD

**Issue by tiennampham23** [KyberNetwork/evmlistener#65]
(Because I don't have any permission to push code into this repository, I create an issue)

Caching go.mod download layer to build the image faster. On `BUILDER` stage, add this line

```Dockerfile
## BUILDER
FROM golang:1.19-bullseye as builder

WORKDIR /src

## Caching go.mod download
COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o app ./cmd/listener
```

**Comment by tiennampham23** [comment]
@hiepnv90 PTAL

**Comment by hiepnv90** [comment]
Added trading team members to this repo, you can push code and create PR.
